/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/IP13PROOR.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.54}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.1, 1.45, -0.26]} scale={0.04}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['GLASS.001']} />
            <mesh geometry={nodes.Object_11.geometry} material={materials['Lenscover.001']} />
            <mesh geometry={nodes.Object_12.geometry} material={materials['material.001']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Display.001']} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Lens.001']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['material_11.001']} />
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Black.001']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Back.001']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['GOLD.001']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['BARRES.001']} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['Labber.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/IP13PROOR.glb')
